name: pathfinder
description: Backend per la gestione utenti e permessi
version: 1.0.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  mysql1: ^0.20.0
  bcrypt: ^1.1.3
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  shelf_cors_headers: ^0.1.5
  

dev_dependencies:
  lints: ^5.1.1
